name: the_recipes
description: "Aplicación de recetas de cocina"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.2
  image_picker: ^1.0.7
  lottie: ^3.3.1
  material_dialogs: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/logo/

