name: the_recipes
description: "Aplicación de recetas de cocina"
publish_to: "none"
version: 1.3.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  archive: ^4.0.7
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  envied: ^1.1.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.4.0
  flutter_native_splash: ^2.4.4
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.2
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  image_picker: ^1.0.7
  lottie: ^3.3.1
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  file_picker: ^8.1.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.15
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/logo/
    - assets/messages/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#18181b"
  image: assets/logo/Icon.png
  android_12:
    color: "#ffffff"
    color_dark: "#18181b"
    image: assets/logo/Icon.png
