name: the_recipes
description: "Aplicación de recetas de cocina"
publish_to: "none"
version: 2.0.0+3

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  archive: ^4.0.7
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.4.0
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.2
  image_picker: ^1.2.0
  lottie: ^3.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  file_picker: ^10.3.2
  http: ^1.5.0
  appwrite: ^18.0.0
  pretty_qr_code: ^3.5.0
  share_plus: ^11.1.0
  app_links: ^6.4.1
  screen_brightness: ^2.1.7
  flutter_riverpod: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.9.3
  build_runner: ^2.7.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/logo/
    - assets/messages/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#18181b"
  image: assets/logo/Icon.png
  android_12:
    color: "#ffffff"
    color_dark: "#18181b"
    image: assets/logo/Icon.png
